[compat]
IntervalArithmetic = "<0.22.32"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CFTime = "179af706-886a-5703-950a-314cd64e0468"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ClimaOcean = "0376089a-ecfe-4b0e-a64f-9c555d74d754"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"

[extras]
gmmlib_jll = "09858cae-167c-5acb-9302-fddc6874d481"
libigc_jll = "94295238-5935-5bd7-bb0f-b00942e9bdd5"

[preferences.NEO_jll]
libigdrcl_path = "/usr/lib64/intel-opencl/libigdrcl.so"
libze_intel_gpu_path = "/usr/lib64/libze_intel_gpu.so.1"

[preferences.gmmlib_jll]
libigdgmm_path = "/usr/lib64/libigdgmm.so"

[preferences.libigc_jll]
libiga_path = "/opt/aurora/24.347.0/oneapi/debugger/latest/opt/debugger/lib/libiga64.so"
libigc_path = "/opt/aurora/24.347.0/oneapi/vtune/2025.0/bin64/gma/GTPin/Profilers/ocloc/Bin/intel64/libigc.so"
libigdfcl_path = "/opt/aurora/24.347.0/oneapi/vtune/2025.0/bin64/gma/GTPin/Profilers/ocloc/Bin/intel64/libigdfcl.so"
libopencl_clang_path = "/opt/aurora/24.347.0/oneapi/vtune/2025.0/bin64/gma/GTPin/Profilers/ocloc/Bin/intel64/libopencl-clang.so"

[preferences.oneAPI_Level_Zero_Loader_jll]
libze_loader_path = "/usr/lib64/libze_loader.so"
libze_validation_layer_path = "/usr/lib64/libze_validation_layer.so"
